### PR TITLE
req

### PR DESCRIPTION
**Pull request by drmastermind**

### CODE REVIEW

**Comment by scottdware** [comment]
@drmastermind There have been a lot of changes since you first opened this pull request. Can you resolve the conflicting files as noted above, and try again?

**Comment by kenmaglio** [comment]
So I don't think merging in this stuff from F5 is a good option. We will be actively working ( myself and the guys at WWT) to start implementing the F5 GTM module here - done in the style Scott has started if you want to wait a bit. ( couple weeks ).
6

**Comment by scottdware** [comment]
> So I don't think merging in this stuff from F5 is a good option. We will be actively working ( myself and the guys at WWT) to start implementing the F5 GTM module here - done in the style Scott has started if you want to wait a bit. ( couple weeks ).
> 6

I agree, Kenneth!

**Comment by kenmaglio** [comment]
This would now conflict with the package as it's starting to implement GTM correctly ( the F5devcentral stuff doesn't even work as they didn't take into account how iControlPath works and made resource names `wideip/a` which breaks the uri assembler )

This package also has a completely working scenario now for GTM. 
@scottdware -- kill this PR?

**Pull request closed without merging**
