### PR TITLE
Support more profiles and other small fixes

### PR DESCRIPTION
**Pull request by zlesnr**

### CODE REVIEW

**Comment by zlesnr** [comment]
Clearly I'm not understanding the tests.  Perhaps I should break this up?

**Comment by zlesnr** [comment]
`go test -v -run TestLtmSuite/TestGetNonExistentPolicy` passes locally.  Is anyone able to tell me why this test doesn't pass here?

**Comment by zlesnr** [comment]
@scottdware I've looked at the failing test here, but I've not made changes to the ApiCall function in bigip.go.  Can you help track down why this is failing?  If this PR can get passing, is it acceptable?

**Comment by scottdware** [comment]
Let me see what I can't find, as to why this is failing.

**Comment by scottdware** [comment]
Looks like for some reason it was failing on the "tip" validation in Travis-CI. I tested this locally as well and didn't run into any issues. I removed that check from the .yml file, so we should be good now. I will merge this.

**Comment by zlesnr** [comment]
Thanks for the merge @scottdware.

**Comment by scottdware** [comment]
My pleasure! Thanks for all the continued contributions and advancements!

**Pull request merged**
