### PR TITLE
Support for (internal) data groups

### PR DESCRIPTION
**Pull request by Ibmurai**
Hi,
I've added support for working with internal data groups.
Please review, and let's discuss any further changes I need to make :)

### CODE REVIEW

**Comment by Ibmurai** [comment]
Oh, btw I think this requires API version 11.6+, so the README might need to be updated to reflect this...

**Comment by Ibmurai** [comment]
Questions, comments, concerns, deadly silence?

**Comment by scottdware** [comment]
I'll get this merged today. My apologies on the delay...been a crazy month so far! Thank you for your contributions, @Ibmurai!

**Comment by Ibmurai** [comment]
@scottdware Hehe no need to apologize! ;) But it's great that you merged it! :) Thanks.

**Pull request merged**
