### PR TITLE
Add token authentication

### PR DESCRIPTION
**Pull request by ivey**
```bigip.UseTokenAuth(loginReference)``` will setup the session object to use token auth instead of basic auth

### CODE REVIEW

**Comment by RobWC** [comment]
This will let us use TACACS+ or LDAP for the REST API. Unfortunately it requires the token auth. Please see [here](https://devcentral.f5.com/wiki/icontrol.authentication_with_the_f5_rest_api.ashx)

**Comment by RobWC** [comment]
Once completed I am going to add this to [the terraform provider](https://github.com/RobWC/terraform-provider-bigip) via a pull request.

**Comment by aburnett** [comment]
Looks good, one thought: As it is today setting auth credentials is part of creating a new session. I feel like setting token based auth fits in that paradigm and as such this addition would be a better fit as a new method next to `NewSession` instead of a toggle on an existing instance. 

Basically taking what you have out of BigIP and call it something like `NewTokenSession(host, user, pass, loginReference string)`. 

Thoughts?

**Comment by scottdware** [comment]
I agree with Adam. Having a new session based on this method of authentication fits better, IMO.

**Comment by ivey** [comment]
That was our original thought, and then I saw that the new method would have the same constructor - because I had forgotten about the login reference. When I added that I didn't look at that part again.

Will make this change shortly.

**Comment by scottdware** [comment]
Nice work, @ivey! This is a nice feature to add.

**Pull request merged**
